language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_install:
    - printf "\n" | pecl install imagick

install:
    - composer install --no-interaction

before_script:
    - printf "\n" | pecl install imagick

script:
    - phpunit
