language: php

php:
    - 5.4
    - 5.5
    - 5.6

install:
    - sudo apt-get install imagemagick php5-imagick
    - composer install

before_script:
    - printf "\n" | pecl install imagick

script:
    - phpunit
