language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_install:
    - pecl install imagick
    - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install --no-interaction

script:
    - phpunit
