language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_install:
    - sudo apt-get update
    - sudo apt-get install php5-imagick

install:
    - composer install --no-interaction

script:
    - phpunit
